# Generated by Django 3.1.3 on 2020-11-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='subject',
            field=models.ManyToManyField(to='journal.Subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='journal.Subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assessment',
            field=models.CharField(choices=[('CR', 'Зачет'), ('DF', 'Дифференцированный зачет'), ('EX', 'Экзамен')], default='CR', max_length=2, verbose_name='Форма контроля'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.department', verbose_name='Кафедра'),
        ),
    ]
